"""Fix UUID type for tutoring_sessions

Revision ID: 01dea4ffd7f4
Revises: cff1379e489f
Create Date: 2025-05-10 23:31:07.773450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01dea4ffd7f4'
down_revision = 'cff1379e489f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutoring_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timeslot_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('tutor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['timeslot_id'], ['time_slots.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tutoring_session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutoring_session',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timeslot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tutor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name='tutoring_session_student_id_fkey'),
    sa.ForeignKeyConstraint(['timeslot_id'], ['time_slots.id'], name='tutoring_session_timeslot_id_fkey'),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], name='tutoring_session_tutor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tutoring_session_pkey')
    )
    op.drop_table('tutoring_sessions')
    # ### end Alembic commands ###
