"""Add tutor_class table

Revision ID: 2aa810307620
Revises: 34bf72832c90
Create Date: 2025-03-19 05:45:26.550206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa810307620'
down_revision = '34bf72832c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor_class',
    sa.Column('tutor_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.tutor_id'], ),
    sa.PrimaryKeyConstraint('tutor_id', 'class_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutor_class')
    # ### end Alembic commands ###
