"""empty message

Revision ID: 5898b136b3cc
Revises: 01dea4ffd7f4
Create Date: 2025-05-10 23:32:20.418617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5898b136b3cc'
down_revision = '01dea4ffd7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutoring_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timeslot_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('tutor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['timeslot_id'], ['time_slots.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tutoring_sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutoring_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timeslot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tutor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name='tutoring_sessions_student_id_fkey'),
    sa.ForeignKeyConstraint(['timeslot_id'], ['time_slots.id'], name='tutoring_sessions_timeslot_id_fkey'),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], name='tutoring_sessions_tutor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tutoring_sessions_pkey')
    )
    op.drop_table('tutoring_session')
    # ### end Alembic commands ###
