"""empty message

Revision ID: 76b67447abdc
Revises: 2aa810307620
Create Date: 2025-04-01 22:11:57.690441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b67447abdc'
down_revision = '2aa810307620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_subject', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['subject_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
