"""Added unique constraint names

Revision ID: d430de779502
Revises: 76b67447abdc
Create Date: 2025-04-01 22:33:26.448240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd430de779502'
down_revision = '76b67447abdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_subject', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_class_subject_subject_name', ['subject_name'])

    with op.batch_alter_table('tutor_class', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tutor_class_tutor_class', ['tutor_id', 'class_id'])

    with op.batch_alter_table('tutor_subject', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tutor_subject_tutor_subject', ['tutor_id', 'subject_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_subject', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tutor_subject_tutor_subject', type_='unique')

    with op.batch_alter_table('tutor_class', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tutor_class_tutor_class', type_='unique')

    with op.batch_alter_table('class_subject', schema=None) as batch_op:
        batch_op.drop_constraint('uq_class_subject_subject_name', type_='unique')

    # ### end Alembic commands ###
